name: Run tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install FUSE
      run: |
        sudo apt-get update
        sudo apt-get install -y fuse libfuse2
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fusepy click pytest
    - name: Run tests
      run: pytest -s -vv
